### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by bee3205** [zzhougy/jianzhi-server#1]
求助大佬，为什么运行不出来，方便解答一下吗

**Comment by bee3205** [comment]
> 求助大佬，为什么运行不出来，方便解答一下吗

显示以下报错
class lombok.javac.apt.LombokProcessor (in unnamed module @0x35ef65e2) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x35ef65e2

**Comment by zzhougy** [comment]
我帮你看看 留个微信





------------------ 原始邮件 ------------------
发件人: bee3205 ***@***.***&gt;
发送时间: 2024年2月29日 18:50
收件人: zzhougy/jianzhi-server ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[zzhougy/jianzhi-server] 无法运行 (Issue #1)





  
求助大佬，为什么运行不出来，方便解答一下吗
  
显示以下报错
 class lombok.javac.apt.LombokProcessor (in unnamed module @0x35ef65e2) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x35ef65e2

**Comment by bee3205** [comment]
> 我帮你看看 留个微信
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: bee3205 ***@***.***&gt; 发送时间: 2024年2月29日 18:50 收件人: zzhougy/jianzhi-server ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[zzhougy/jianzhi-server] 无法运行 (Issue #1) 求助大佬，为什么运行不出来，方便解答一下吗 显示以下报错 class lombok.javac.apt.LombokProcessor (in unnamed module @0x35ef65e2) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x35ef65e2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;



> 我帮你看看 留个微信
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: bee3205 ***@***.***&gt; 发送时间: 2024年2月29日 18:50 收件人: zzhougy/jianzhi-server ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[zzhougy/jianzhi-server] 无法运行 (Issue #1) 求助大佬，为什么运行不出来，方便解答一下吗 显示以下报错 class lombok.javac.apt.LombokProcessor (in unnamed module @0x35ef65e2) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x35ef65e2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

a17666033205  感谢大佬
